{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "11d96333_65651c7f",
        "filename": "split_cl.py",
        "patchSetId": 1
      },
      "lineNbr": 125,
      "author": {
        "id": 1560543
      },
      "writtenOn": "2025-04-17T20:32:25Z",
      "side": 1,
      "message": "nit: I\u0027d rather this return None and let caller to assert. Also, since we are returning three variables, consider returning named tuple or object.",
      "revId": "c01a53f0fcad27ded11e563ad8f6750e6973b6a2",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "139796be_2e416741",
        "filename": "split_cl.py",
        "patchSetId": 1
      },
      "lineNbr": 125,
      "author": {
        "id": 3481761
      },
      "writtenOn": "2025-04-17T20:35:57Z",
      "side": 1,
      "message": "Ack, but returning None is tricky because there are multiple failure conditions. IMO the weirder part is that this is the only place where we assert, as opposed to some other failure strategy. May change that in a followup CL.\n\nI think the boilerplace of making a named object just to return it from one function is a bit too high. Though I am dissatisfied with the number of arguments these functions have, so if I end up consolidating them it might make more sense.",
      "parentUuid": "11d96333_65651c7f",
      "revId": "c01a53f0fcad27ded11e563ad8f6750e6973b6a2",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}